name: hnefatafl
version: 0.0.0.2

spec-version: 0.35.0
verbatim:
  cabal-version: 2.4

language: GHC2021

include-dirs:
  - "src/Board/"

c-sources:
  - "src/Board/move.c"
  - "src/Board/move.h"

extra-source-files:
  - "src/Board/move.c"
  - "src/Board/move.h"

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - OverloadedRecordDot
  - OverloadedLabels
  - DuplicateRecordFields
  - LambdaCase
  - DerivingVia
  - ImportQualifiedPost

ghc-options:
  - -Wunused-imports
  - -Wall
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Widentities
  - -Wpartial-fields
  - -Wcpp-undef
  - -Wno-orphans
  - -fprint-potential-instances
  - -threaded
  - -O2

dependencies:
  - name: base
    #version: ">=4.15"
    mixin:
      - hiding (Prelude)
  - name: relude
    #version: ">= 1.1.0.0"
    mixin:
      - (Relude as Prelude)

  - aeson
  - array
  - async
  - containers
  - deepseq
  - generic-lens
  - http-media
  - http-types
  - lucid2
  - mtl
  - parallel
  - random
  - raw-strings-qq
  - servant
  - servant-client
  - servant-server
  - servant-websockets
  - split
  - sqlite-simple
  - stm
  - storable-tuple
  - template-haskell
  - text
  - time
  - unagi-chan
  - uuid
  - vector
  - vector-hashtables
  - wai
  - warp
  - websockets
  - wide-word
  - wai-websockets
  - resourcet
  - lens
  - storable-record
  # - QuickCheck
  # - annotated-exception
  # - attoparsec
  # - bytestring
  # - cassava
  # - deepseq
  # - envparse
  # - exceptions
  # - generic-optics
  # - generic-random
  # - http-client
  # - katip
  # - newtype-generics
  # - optics
  # - quickcheck-instances
  # - refined >= 0.7
  # - resourcet
  # - servant-lucid
  # - some

library:
  source-dirs: src
  language: GHC2021

executables:
  hnefatafl:
    main: "Main.hs"
    source-dirs: app
    dependencies:
      - hnefatafl

tests:
  test:
    main: "Main.hs"
    source-dirs: test
    dependencies:
      - hnefatafl
#       - hspec
#       - hspec-contrib
#       - hspec-core
#       - hspec-wai
#       - HUnit
#       - tasty
#       - tasty-discover
#       - tasty-hspec
#       - tasty-hunit
#       - tasty-quickcheck
      - quickcheck-instances
      - QuickCheck

benchmarks:
  board:
    main: "Main.hs"
    source-dirs: bench
    dependencies:
      - hnefatafl
      - criterion
