{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = { sumtypes = false; };
    package = {
      specVersion = "1.10";
      identifier = { name = "derive-storable-plugin"; version = "0.2.3.7"; };
      license = "MIT";
      copyright = "";
      maintainer = "mateusz.p.kloczko@gmail.com";
      author = "Mateusz Kłoczko";
      homepage = "https://www.github.com/mkloczko/derive-storable-plugin/";
      url = "";
      synopsis = "GHC core plugin supporting the derive-storable package.";
      description = "The package helps derive-storable package in forcing compile time evaluation of\nsizes, alignments and offsets.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."ghc" or (errorHandler.buildDepError "ghc"))
          (hsPkgs."ghci" or (errorHandler.buildDepError "ghci"))
          (hsPkgs."derive-storable" or (errorHandler.buildDepError "derive-storable"))
        ];
        buildable = true;
      };
      tests = {
        "c_alignment" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."derive-storable" or (errorHandler.buildDepError "derive-storable"))
            (hsPkgs."derive-storable-plugin" or (errorHandler.buildDepError "derive-storable-plugin"))
            (hsPkgs."hspec" or (errorHandler.buildDepError "hspec"))
            (hsPkgs."QuickCheck" or (errorHandler.buildDepError "QuickCheck"))
            (hsPkgs."ghc" or (errorHandler.buildDepError "ghc"))
            (hsPkgs."ghci" or (errorHandler.buildDepError "ghci"))
          ];
          buildable = true;
        };
      };
      benchmarks = {
        "plugin-benchmark" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."deepseq" or (errorHandler.buildDepError "deepseq"))
            (hsPkgs."criterion" or (errorHandler.buildDepError "criterion"))
            (hsPkgs."derive-storable" or (errorHandler.buildDepError "derive-storable"))
            (hsPkgs."derive-storable-plugin" or (errorHandler.buildDepError "derive-storable-plugin"))
          ] ++ pkgs.lib.optional (compiler.isGhc && compiler.version.lt "8.4") (hsPkgs."text" or (errorHandler.buildDepError "text"));
          buildable = true;
        };
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/derive-storable-plugin-0.2.3.7.tar.gz";
      sha256 = "a7625c50f24434665c8696a06ee380390dc52102a62c19f0a4d0c53244656c41";
    });
  }) // {
    package-description-override = "-- Initial generic-storable-plugin.cabal generated by cabal init.  For\n-- further documentation, see http://haskell.org/cabal/users-guide/\n\nname:                derive-storable-plugin\nversion:             0.2.3.7\nsynopsis:            GHC core plugin supporting the derive-storable package.\ndescription:         The package helps derive-storable package in forcing compile time evaluation of\n                     sizes, alignments and offsets.\nhomepage:            https://www.github.com/mkloczko/derive-storable-plugin/\nlicense:             MIT\nlicense-file:        LICENSE\nauthor:              Mateusz Kłoczko\nmaintainer:          mateusz.p.kloczko@gmail.com\n-- copyright:\ncategory:            Foreign\nbuild-type:          Simple\nextra-source-files:  ChangeLog.md README.md\ncabal-version:       >=1.10\ntested-with:         GHC==8.2.2, GHC==8.4.2, GHC==8.6.5, GHC==8.8.1, GHC==8.10.7, GHC==9.0.2, GHC==9.2.2, GHC==9.4.2, GHC==9.6.1\n\nFlag sumtypes\n  Description:   Use sumtypes within benchmark and tests.\n  Default:       False\n\nlibrary\n  exposed-modules:       Foreign.Storable.Generic.Plugin\n                       , Foreign.Storable.Generic.Plugin.Internal\n                       , Foreign.Storable.Generic.Plugin.Internal.Error\n                       , Foreign.Storable.Generic.Plugin.Internal.Compile\n                       , Foreign.Storable.Generic.Plugin.Internal.GroupTypes\n                       , Foreign.Storable.Generic.Plugin.Internal.Helpers\n                       , Foreign.Storable.Generic.Plugin.Internal.Predicates\n                       , Foreign.Storable.Generic.Plugin.Internal.Types\n  other-extensions:    DeriveGeneric, DeriveAnyClass, PatternGuards\n  build-depends:       base >=4.10 && <5, ghc >= 8.2 && < 9.7, ghci >= 8.2 && < 9.7, derive-storable >= 0.3 && < 0.4\n  hs-source-dirs:      src\n  default-language:    Haskell2010\n\nbenchmark plugin-benchmark\n  type:                exitcode-stdio-1.0\n  hs-source-dirs:      benchmark/\n  default-language:    Haskell2010\n  other-modules:       TestCases, TestCasesOptimized\n  Main-is:             Main.hs\n  build-depends:       base >= 4.10 && < 5, deepseq, criterion >= 1.1.0\n                    ,  derive-storable, derive-storable-plugin\n\n  if flag(sumtypes)\n    cpp-options: -DGSTORABLE_SUMTYPES\n\n  if impl(ghc < 8.4)\n    build-depends: text < 1.2.5.0\n\ntest-suite c_alignment\n  type:                exitcode-stdio-1.0\n\n  hs-source-dirs:      test/Basic, test/Basic/cbits\n  c-sources:           test/Basic/cbits/TestCases.c\n  main-is:             MemoryCSpec.hs\n  other-modules:       TestCases\n  build-depends:       base >= 4.10 && < 5, derive-storable, derive-storable-plugin\n                     , hspec >= 2.4, QuickCheck >= 2.10\n                     , ghc >= 8.2 && < 9.7, ghci >= 8.2 && < 9.7\n\n  default-language:    Haskell2010\n  if flag(sumtypes)\n    cpp-options: -DGSTORABLE_SUMTYPES\n";
  }