name: hnefatafl
version: 0.0.0.2

spec-version: 0.35.0
verbatim:
  cabal-version: 2.4

language: GHC2021

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - OverloadedRecordDot
  - OverloadedLabels
  - DuplicateRecordFields
  - LambdaCase
  - DerivingVia
  - ImportQualifiedPost
  - MultilineStrings

ghc-options:
  - -Wunused-imports
  - -Wall
  - -Werror
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Widentities
  - -Wpartial-fields
  - -Wcpp-undef
  - -Wno-orphans
  - -fprint-potential-instances
  - -threaded
  - -O2
  # Below is a magical incantation that allows linking against archive library ".a" files
  # https://stackoverflow.com/questions/36040366/haskell-cabal-include-static-library
  - -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lhnefatafl" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"

data-files:
  - db/schema.sql

dependencies:
  - name: base
    #version: ">=4.15"
    mixin:
      - hiding (Prelude)
  - name: relude
    #version: ">= 1.1.0.0"
    mixin:
      - (Relude as Prelude)
  - derive-storable
  - derive-storable-plugin
  - sqlite-simple
  - text
  - time
  - ulid
  - effectful
  - effectful-th
  - optics
  - transformers

# executables:
#   app:
#     main: "Main.hs"
#     source-dirs: app
#     dependencies:
#       - hnefatafl
      
library:
  source-dirs: src

tests:
  hnefatafl-test:
    main: "Driver.hs"
    ghc-options:
      - -Wno-missing-export-lists
    source-dirs: test
    build-tools:
        tasty-discover:tasty-discover
    dependencies:
      - hnefatafl
      - hspec
      - hspec-expectations-pretty-diff
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-discover
      - temporary
      - process
      - direct-sqlite
      - optics

# benchmarks:
#   board:
#     main: "Main.hs"
#     source-dirs: bench
#     dependencies:
#       - hnefatafl
#       - criterion
